### ISSUE TITLE
[Crypto Night] #7 霍格華茲的區塊鏈咒語: 解讀 Mimblewimble

### ISSUE THREAD

**Issue by AngelinaHIH** [flowchain/crypto-night#4]
簡介

Mimblewimble!!! ⚡️

出自哈利波特系列叢書，是一種可以讓中咒者無法洩露秘密的咒語。在區塊鏈的世界裡，Mimblewimble 則是數位資產 Beam 和 Grin 的底層協議。作為比特幣協議的改良版，在以 Mimblewimble 建立的區塊鏈網絡中，交易的各項要素都被層層加密隱藏，非交易參與者既查不到交易地址，也查不到交易金額，甚至連中間轉手的交易過程都查不到。

值得注意的是，簡化後的交易過程，使該協議在記錄同等內容的數據時，所耗費的帳本容量和網絡帶寬要遠遠小於比特幣協議，也就是說 Mimblewimble 的隱私性更強，能源消耗更低，究竟 Mimblewimble 是如何做到的？底下使用的密碼學技術有什麼玄機？

本次小聚將由 Jollen 帶領大家一探 Mimblewimble 的底層技術！

資訊

時間：2019 年 03 月 06 日 7pm-9pm
地點：Flowchain 台北總部
地址：台北市忠孝東路 4 段 178 號 7 樓
捷運：忠孝敦化站 3 號出口 步行 1 分鐘
費用：200元(學生可憑有效學生證報到，現場全額退費)

**Comment by loljenchun** [comment]
Done!
